---
version: '3.6'

services:
  wpt-web:
    image: wpt-nginx:94ea2fbe
    ports:
      - "80:80"

  wpt-php:
    image: wpt-php:94ea2fbe

  agent:
    image: baqend/webpagetest-agent:2021-04-08
    cap_add:
      - NET_ADMIN
    environment:
      SERVER_URL: http://wpt-web/work/
      LOCATION: us-east-1-docker
      KEY: 1234567890123456789012345678901234567890
    command: '-v--exit 60'
#    volumes:
#      - type: bind
#        source: /var/run/docker.sock
#        target: /var/run/docker.sock

networks:
  default:


#    command: 'sh -c "exec docker run --rm --cap-add=NET_ADMIN --shm-size=1g --log-driver none baqend/webpagetest-agent:2021-04-08
#     -v -v -v --server http://wpt-web/work/ --location us-east-1-docker --key 1234567890123456789012345678901234567890 --exit 60"'
