---
version: '3.6'

# WEB_TAG=2021-04-13 PHP_TAG=2021-04-13 AGENT_TAG=2021-04-13 LOCATION=eu-central-1 docker stack deploy

services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile-ngix
    image: baqend/webpagetest-nginx:${WEB_TAG}
    ports:
      - "80:80"
    volumes:
      - wpt-results:/var/www/webpagetest/results
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.master == true'

  php:
    build:
      context: ./
      dockerfile: Dockerfile-php
    image: baqend/webpagetest-php:${PHP_TAG}
    volumes:
      - wpt-results:/var/www/webpagetest/results
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.master == true'

  agent:
    image: docker:20.10
    command: 'sh -c "exec docker run --rm --cap-add=NET_ADMIN --shm-size=1g --log-driver none baqend/webpagetest-agent:${AGENT_TAG} --server http://wpt.baqend.com/work/ --location ${LOCATION}-docker --key $$(cat /run/secrets/wpt-key) --exit 60"'
    secrets:
      - wpt-key
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "3"
    deploy:
      mode: global
      placement:
        constraints:
          - 'node.labels.location == ${LOCATION}'
          - 'node.labels.master != true'
          - 'node.labels.prewarmer != true'

networks:
  default:

secrets:
  wpt-key:
    external: true

volumes:
  wpt-results:
